### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tipowol**

### CODE REVIEW

**Comment by KumarGanesha1996** [comment]
hi @Wowol i tink it is spam

**Comment by tipowol** [comment]
hi @KumarGanesha1996  i just want to win back my friendship with wowol back :'(

**Comment by KumarGanesha1996** [comment]
hi @tipowol i feel u bro good luck

**Comment by tipowol** [comment]
@KumarGanesha1996 please do NOT assume my gender >:(

**Comment by KumarGanesha1996** [comment]
kek

**Comment by v3ctor** [comment]
You are so rude sir, I could be a woman.

**Comment by tipowol** [comment]
You are so rude sir, I could be a woman.

**Comment by KumarGanesha1996** [comment]
prove that @tipowol send me bobs

**Comment by tipowol** [comment]
@Wowol help me! I am being harassed!!

**Comment by Wowol** [comment]
sorry i can't accept changes from someone who doesn't care
about
me
all the
time

see u never

**Comment by v3ctor** [comment]
>:(

**Comment by tipowol** [comment]
>:(

**Pull request closed without merging**
